remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: true
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Frontend Developer

locations:
  - Hyderabad
apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: ollama
llm_model: 'llama3.2:3b'
llm_api_url: 'http://127.0.0.1:11434'

# New Features
follow_up_emails:
  enabled: true
  interval: 7  # Days

job_matching_algorithm:
  match_threshold: 0.75  # Minimum match score to consider a job
  keywords:
    - Python
    - Java
    - AI
    - Frontend
    - Frontend Development
    - Data Analysis
    - Software Development

ui_enhancements:
  dashboard: true
  custom_themes: true
  notifications: true

performance_optimization:
  cache_results: true
  parallel_processing: true

portal_name: LinkedIn

job_portals:
  - name: LinkedIn
    login_url: "https://www.linkedin.com/login"
    feed_url: "https://www.linkedin.com/feed"
    login_element: "password"
    feed_element: "share-box-feed-entry__trigger"
    profile_image_xpath: "//img[contains(@alt, 'Photo of')]"
    security_check_url: "https://www.linkedin.com/checkpoint/challengesV2/"
